### ISSUE TITLE
Badge updates

### ISSUE THREAD

**Issue by adamsilver** [ministryofjustice/mojdt-frontend#47]
I think the default badge should be small so that we encourage their use over more prominent badges (and to differentiate our badge more clearly against the Tag component).

Default, big badges will break in contexts that we use at HMCTS. But small badges won't break in places where the big badges are used (they take up less space).

Instead of `padding: 4px 8px` use `padding: 0 govuk-spacing(1);` which follows the space system.

Don't double up on classes for things (like `--red` and `--error`) as we don't have backwards compatibility issues to contend with right now. This is our opportunity to have learner code and one way of doing the same thing and is consistent with colours that don't have alternative names. I'd suggest be explicit by using just the colour names.

**Comment by whatterz** [comment]
The additional classes names, for example `--warning` and `--error`, are to apply meaning to the colour, rather than backwards compatibility. So, if a designer wants to implement an info box, they'd need to use `--information` rather than `--blue` or perhaps `--grey`. We intentionally want them to use a class with a specified colour.

**Comment by whatterz** [comment]
Fixed
